### ISSUE TITLE
4. Triển khai kế hoạch lên Project Tasks của FocalBoard

### ISSUE THREAD

**Issue by LeThiKimLe** [LeThiKimLe/Group16-s-LabelStudio_Project#21]

**Comment by NguyenThiCamNguyen** [comment]
Day01: đã hoàn thành triển khai kế hoạch lên Project Tasks của FocalBoard
Link minh chứng :
https://docs.google.com/document/d/15BKGYqeuOqW_Dtjsq76F72sjxYfqJ4ND/edit?usp=sharing&ouid=108438246333990327319&rtpof=true&sd=true
