### ISSUE TITLE
5. Triển khai kế hoạch thành các MileStone, Issues, Tasks trên GitHub 

### ISSUE THREAD

**Issue by LeThiKimLe** [LeThiKimLe/Group16-s-LabelStudio_Project#22]

**Comment by NguyenThiCamNguyen** [comment]
Day02 đã hoàn thành task Triển khai kế hoạch thành các MileStone, Issues, Tasks trên GitHub
Link minh chứng:
https://docs.google.com/document/d/1rv7YHm8GWtaD7jfW1ywuH1APH_iKu0gs/edit?usp=sharing&ouid=108438246333990327319&rtpof=true&sd=true
