### ISSUE TITLE
6. Tìm hiểu cách tổ chức database của Label Studio

### ISSUE THREAD

**Issue by LeThiKimLe** [LeThiKimLe/Group16-s-LabelStudio_Project#23]

**Comment by NguyenThiCamNguyen** [comment]
Day03 đã hoàn thành task Tìm hiểu cách tổ chức database của Label Studio
Link minh chứng:
https://docs.google.com/document/d/1Uwym9m2lUPzYzzo_vxxMaxBksgWecs9Y/edit?usp=sharing&ouid=108438246333990327319&rtpof=true&sd=true
