### ISSUE TITLE
Tìm hiểu và cài đặt Label Studio local với Docker

### ISSUE THREAD

**Issue by LeThiKimLe** [LeThiKimLe/Group16-s-LabelStudio_Project#3]
- [x] 1.1. Tìm hiểu và cài đặt Docker
- [x] 1.2. Tìm hiểu và cài đặt Label Studio

**Comment by NguyenThiCamNguyen** [comment]
Hoàn thành task 1

**Comment by LeThiKimLe** [comment]
- [ ] Tìm hiểu và cài đặt Docker
- [ ] Tìm hiểu và cài đặt Label Studio

**Comment by NguyenThiCamNguyen** [comment]
Day 1 của Week 1 hoàn thành:
task1: Tìm hiểu và cài đặt docker
task2: Tìm hiểu và cái đặt Label Studio
Link minh chứng cho cả task 1 và task 2: https://docs.google.com/document/d/1dNEyls5JVKdfzKAE9WsOjJXhSfBBLJCp/edit?usp=sharing&ouid=108438246333990327319&rtpof=true&sd=true

**Comment by LeThiKimLe** [comment]
Day 1: Hoàn thành tìm hiểu và cài đặt Docker
Link minh chứng: https://docs.google.com/document/d/1vcY7VTl01I1eXk5QPvr5YZCf5LWFou399m3Sr6gIplk/edit?usp=sharing

**Comment by LeThiKimLe** [comment]
Day 2: Hoàn thành task 1.2
Link minh chứng: https://docs.google.com/document/d/1vcY7VTl01I1eXk5QPvr5YZCf5LWFou399m3Sr6gIplk/edit?usp=sharing
