### ISSUE TITLE
8. Tìm hiểu cách vẽ activity diagram

### ISSUE THREAD

**Issue by LeThiKimLe** [LeThiKimLe/Group16-s-LabelStudio_Project#32]

**Comment by NguyenThiCamNguyen** [comment]
Link minh chứng thực hiện Issue Tìm hiểu cách vẽ activity diagram 
https://docs.google.com/document/d/1106L5MqtMcFMGDDoz0uMA458ai8bYvnQ/edit?usp=sharing&ouid=108438246333990327319&rtpof=true&sd=true
