### ISSUE TITLE
2. Demo các chức năng nâng cao (P1)

### ISSUE THREAD

**Issue by LeThiKimLe** [LeThiKimLe/Group16-s-LabelStudio_Project#34]

**Comment by LeThiKimLe** [comment]
- [ ] 1. Phân quyền người dùng với các role tương ứng.
- [ ] 2. Phân task label cho các annotator.

**Comment by NguyenThiCamNguyen** [comment]
Link minh chứng thực hiện Issue Demo các chức năng nâng cao (P1)
https://docs.google.com/document/d/1x9lbmbJFnfwraciFzf_dXoRtwdgDIbaG/edit?usp=sharing&ouid=108438246333990327319&rtpof=true&sd=true
