### ISSUE TITLE
W4_10. Quay video demo chức năng đã cài đặt (P1)

### ISSUE THREAD

**Issue by LeThiKimLe** [LeThiKimLe/Group16-s-LabelStudio_Project#55]
- [ ]  Chức năng tạo project
- [ ]  Import dữ liệu
- [ ] Tích hợp Machine Learning

**Comment by NguyenThiCamNguyen** [comment]
Minh chứng thực hiện:
https://drive.google.com/file/d/1-47-urWy9ZxT-DWilBVcfk9YRKSgIqSm/view?usp=sharing
