### ISSUE TITLE
W4_12. Lập danh sách chức năng đã tìm hiểu và cài đặt

### ISSUE THREAD

**Issue by LeThiKimLe** [LeThiKimLe/Group16-s-LabelStudio_Project#57]

**Comment by NguyenThiCamNguyen** [comment]
Minh chứng thực hiện:
https://docs.google.com/document/d/1aUIxsgEUgfH5ncvmFCm6mfVm4RrDeTK9/edit?usp=sharing&ouid=108438246333990327319&rtpof=true&sd=true
