### ISSUE TITLE
W5_1. Fix lỗi giao diện khi chạy code local

### ISSUE THREAD

**Issue by LeThiKimLe** [LeThiKimLe/Group16-s-LabelStudio_Project#62]

**Comment by NguyenThiCamNguyen** [comment]
Minh chứng thực hiện:
https://docs.google.com/document/d/1_zPxZCxxVZvRWUdtB6Jf20XeF6TGoRC3/edit?usp=share_link&ouid=108438246333990327319&rtpof=true&sd=true
