### ISSUE TITLE
W7_4. Viết file quản lý rủi ro

### ISSUE THREAD

**Issue by LeThiKimLe** [LeThiKimLe/Group16-s-LabelStudio_Project#75]

**Comment by NguyenThiCamNguyen** [comment]
Link document quản lý rủi ro
https://docs.google.com/document/d/1LQwO5RQTYO9rq_j2Vqghg0CL9zh56wtx/edit?usp=sharing&ouid=108438246333990327319&rtpof=true&sd=true
